[project]
name = "aria"
version = "0.0.8"
description = "Home_server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=49.0.0",
    "fastapi[standard]>=0.139.0",
    "huggingface-hub>=1.24.0",
    "kittentts",
    "openai>=2.41.1",
    "psutil>=7.2.2",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
    "sounddevice>=0.5.5",
]

[project.scripts]
aria = "cli.main:main"

[tool.uv.sources]
kittentts = { git = "https://github.com/KittenML/KittenTTS.git", rev = "main" }
