/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#5edac7",
        "inverse-on-surface": "#313030",
        "background": "#131313",
        "on-primary-container": "#541400",
        "on-secondary": "#2c3230",
        "outline": "#a38c85",
        "primary-fixed-dim": "#ffb59e",
        "outline-variant": "#55433d",
        "secondary": "#c2c8c5",
        "primary-fixed": "#ffdbd0",
        "on-secondary-fixed": "#171d1b",
        "on-background": "#e5e2e1",
        "surface-tint": "#ffb59e",
        "on-primary-fixed-variant": "#7a2f15",
        "surface-variant": "#353535",
        "primary-container": "#d97757",
        "on-error": "#690005",
        "tertiary-container": "#09a493",
        "error": "#ffb4ab",
        "on-primary": "#5c1902",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-secondary-container": "#b1b6b4",
        "on-tertiary": "#003731",
        "on-secondary-fixed-variant": "#424846",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-fixed-variant": "#005047",
        "secondary-fixed": "#dee4e1",
        "on-surface-variant": "#dbc1b9",
        "surface-container-high": "#2a2a2a",
        "inverse-primary": "#99462a",
        "secondary-fixed-dim": "#c2c8c5",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-container": "#00312b",
        "surface": "#131313",
        "tertiary-fixed-dim": "#5edac7",
        "on-primary-fixed": "#390b00",
        "secondary-container": "#424846",
        "surface-dim": "#131313",
        "surface-container": "#20201f",
        "primary": "#ffb59e",
        "on-tertiary-fixed": "#00201c",
        "on-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "surface-container-highest": "#353535",
        "surface-bright": "#393939",
        "tertiary-fixed": "#7df7e3"
      },
      fontFamily: {
        "headline": ["VT323"],
        "body": ["Space Grotesk"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "0px"},
    },
  },
  plugins: [],
}

